name: Build

on:
  pull_request:
    branches:
      - dockerbuild-fix
  push:
    branches:
      - dockerbuild-fix
    tags:
      - v*
  schedule:
    - cron: '0 16 * * *' # Every day at 16:00 UTC (~09:00 PT)

jobs:
  build:
    name: Build releasable package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '15.x'

      - name: Install dependencies and compile
        run: ./scripts/build.npm.sh

      - name: Package the build
        run: |
          mv dist codex-frontend
          tar -czvf codex-frontend.tar.gz codex-frontend/

      - uses: actions/upload-artifact@v2
        with:
          name: codex-frontend
          path: codex-frontend.tar.gz
          # default:
          # retention-days: 90

  deploy:
    name: Docker image build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        if: github.event_name == 'schedule'
        with:
          ref: develop

      - uses: actions/checkout@v2
        if: github.event_name != 'schedule'

      - uses: docker/setup-qemu-action@v1
        name: Set up QEMU
        id: qemu
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx
        id: buildx

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      # Build images
      - name: Build Codex
        run: |
          ./scripts/buildx.docker.sh

      # Log into container registries
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: wildmebot
          password: ${{ secrets.WBIA_WILDMEBOT_DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Push tagged image (version tag + latest) to registries
      - name: Tagged Docker Hub
        if: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v') }}
        run: |
          VERSION=$(echo ${GITHUB_REF} | sed 's#.*/v##')
          ./scripts/buildx.docker.sh -t ${VERSION}
          ./scripts/buildx.docker.sh -t latest

      - name: Tagged GHCR
        if: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v') }}
        run: |
          VERSION=$(echo ${GITHUB_REF} | sed 's#.*/v##')
          ./scripts/buildx.docker.sh -t ${VERSION} -r ghcr.io/wildmeorg/codex-frontend
          ./scripts/buildx.docker.sh -t latest -r ghcr.io/wildmeorg/codex-frontend

      # Push stable image (main tag) to registries
      - name: Stable Docker Hub
        if: github.ref == 'refs/heads/dockerbuild-fix'
        run: |
          ./scripts/buildx.docker.sh -t dockerbuild-fix

      - name: Stable GHCR
        if: github.ref == 'refs/heads/dockerbuild-fix'
        run: |
          ./scripts/buildx.docker.sh -t dockerbuild-fix -r ghcr.io/wildmeorg/codex-frontend

      # Push bleeding-edge image (develop tag) to registries
      - name: Bleeding Edge Docker Hub
        if: github.ref == 'refs/heads/develop'
        run: |
          ./scripts/buildx.docker.sh -t develop

      - name: Bleeding Edge GHCR
        if: github.ref == 'refs/heads/develop'
        run: |
          ./scripts/buildx.docker.sh -t develop -r ghcr.io/wildmeorg/codex-frontend

      # Push nightly image (nightly tag) to registries
      - name: Nightly Docker Hub
        if: github.event_name == 'schedule'
        run: |
          ./scripts/buildx.docker.sh -t nightly

      - name: Nightly GHCR
        if: github.event_name == 'schedule'
        run: |
          ./scripts/buildx.docker.sh -t nightly -r ghcr.io/wildmeorg/codex-frontend

      # Notify status in Slack
      - name: Slack Notification
        if: ${{ failure() && github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v') }}
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: dev-houston
          SLACK_COLOR: '#FF0000'
          SLACK_ICON: https://avatars.slack-edge.com/2020-03-02/965719891842_db87aa21ccb61076f236_44.png
          SLACK_MESSAGE: 'Tagged / Latest Docker build of Codex Frontend failed :sob:'
          SLACK_USERNAME: "GitHub CI"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notification
        if: ${{ failure() && github.ref == 'refs/heads/dockerbuild-fix' }}
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: dev-houston
          SLACK_COLOR: '#FF0000'
          SLACK_ICON: https://avatars.slack-edge.com/2020-03-02/965719891842_db87aa21ccb61076f236_44.png
          SLACK_MESSAGE: 'Stable Docker build of Codex Frontend failed :sob:'
          SLACK_USERNAME: "GitHub CI"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notification
        if: ${{ failure() && github.ref == 'refs/heads/develop' }}
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: dev-houston
          SLACK_COLOR: '#FF0000'
          SLACK_ICON: https://avatars.slack-edge.com/2020-03-02/965719891842_db87aa21ccb61076f236_44.png
          SLACK_MESSAGE: 'Bleeding Edge Docker build of Codex Frontend failed :sob:'
          SLACK_USERNAME: "GitHub CI"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notification
        if: ${{ failure() && github.event_name == 'schedule' }}
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: dev-houston
          SLACK_COLOR: '#FF0000'
          SLACK_ICON: https://avatars.slack-edge.com/2020-03-02/965719891842_db87aa21ccb61076f236_44.png
          SLACK_MESSAGE: 'Nightly Docker build of Codex Frontend failed :sob:'
          SLACK_USERNAME: "GitHub CI"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
